quarkus:
  application:
    name: user-profile-manager

  http:
    port: ${SERVER_PORT:8080}
    root-path: /user-manager

  datasource:
    db-kind: postgresql
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/homeapp}
    username: ${DB_USERNAME:user_manager_svc}
    password: ${DB_PASSWORD:}

  hibernate-orm:
    database:
      default-schema: user_manager
    log:
      sql: false

  liquibase:
    default-schema-name: user_manager
    liquibase-schema: user_manager
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml

  container-image:
    group: ghcr.io/jlmonteiro
    name: user-profile-manager
    base-jvm-image: eclipse-temurin:21-jre-alpine
    labels:
      org.opencontainers.image.source: https://github.com/jlmonteiro/user-profile-manager

  jackson:
    serialization:
      write-dates-as-timestamps: false

  log:
    level: INFO
    category:
      "com.jorgemonteiro":
        level: DEBUG
